@startuml DiseñoAN
!theme toy

title Diseño Arquitectónico de Alto Nivel \n (Sistema de Transcripción Braille - Python/Flask)

skinparam component {
    FontSize 14
    BorderColor #A93226
    BackgroundColor #FADBD8
}
skinparam database {
    BackgroundColor #AED6F1
    BorderColor #3498DB
}

actor Usuario as User #FFCC99

package "Aplicación Web (Python/Flask)" as App {
    
    frame "Capa de Presentación" as CP {
        component "Interfaz de Usuario" as UI #D5F5E3
        note right of UI
            HTML/CSS/JS
            (Entrada de Texto)
        end note
    }

    frame "Capa de Lógica de Negocio" as CLN {
        component "Servidor Flask" as Flask #F7DC6F
        component "Motor de Transcripción" as Core #F7DC6F
        
        Flask --> Core : Ejecuta Lógica
    }

    frame "Capa de Datos" as CD {
        database "Mapeos Braille" as Mapeo #F9E79F
        note bottom of Mapeo
            Archivos de Configuración (JSON/PY)
        end note
    }
}

package "Subsistema de Salida" as Output {
    component "Generador de Señalética" as GS #D5F5E3
    file "Archivo PDF/SVG" as File #AED6F1
}

' === Relaciones/Flujos === '

User --> UI : Introduce Texto
UI --> Flask : Solicitud HTTP (RF-001)

Flask --> Core : Procesa Solicitud
Core --> Mapeo : Consulta Reglas (Alfabeto, Números)

Mapeo -up-> Core : Devuelve Reglas

Core --> UI : Muestra Resultado (HTML)

' Flujo de Señalética (RF-004) '
Core --> GS : Lógica de Renderizado
GS --> File : Crea Documento Vectorial
File .right.> UI : Descarga de Archivo

@enduml